### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by mrjjwright** [Freak613/1more#2]
What kind of performance are you seeing right now compared to your previous work?

**Comment by Freak613** [comment]
I submitted this library to js-framework-benchmark, so you can check its results in last PR:
https://github.com/krausest/js-framework-benchmark/pull/870
or in current results table:
https://krausest.github.io/js-framework-benchmark/current.html

**Comment by mrjjwright** [comment]
Thanks!

**Comment by Freak613** [comment]
Comparing to `stage0`, this library going to be slower because it trades part of performance for convenient features and better developer experience.

**Comment by mrjjwright** [comment]
Well it doesn't appear to be slow at all.   Looks like awesome perf as
usual.
